In [1]:
f(x) = x^2

f (generic function with 1 method)

In [2]:
f(x::Int)::Int = x^2

f (generic function with 2 methods)

In [3]:
f(x::T) where T <: Number = x^2

f (generic function with 3 methods)

In [6]:
function f(x::T) where T <: Number 
    return x^2
end

f (generic function with 3 methods)

In [4]:
methods(f)

# 3 methods for generic function "f":
[1] f(x::Int64) in Main at In[2]:1
[2] f(x::T) where T<:Number in Main at In[3]:1
[3] f(x) in Main at In[1]:1

In [7]:
@which f("hello ")

f(x) in Main at In[1]:1

In [8]:
@which f(2.3)

f(x::T) where T<:Number in Main at In[6]:1

In [9]:
@which f(true)

f(x::T) where T<:Number in Main at In[6]:1

In [10]:
typeof(true)

Bool

In [11]:
supertype(Bool)

Integer

In [12]:
@which f(24)

f(x::Int64) in Main at In[2]:1

In [13]:
methods(rand)

# 70 methods for generic function "rand":
[1] rand() in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:256
[2] rand(dims::Integer...) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:277
[3] rand(rng::Random.AbstractRNG, sp::Random.Masked) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:234
[4] rand(rng::Random.AbstractRNG, sp::Random.SamplerRangeFast{UInt32, T}) where T in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:220
[5] rand(rng::Random.AbstractRNG, sp::Random.SamplerRangeFast{UInt64, T}) where T in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:227
[6] rand(rng::Random.AbstractRNG, sp::Random.SamplerRangeFast{UInt128, T}) where T in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:234
[7] rand(rng::Random.AbstractRNG, ::Random.UniformT{T}) where T in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:242
[8] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt104{UInt128}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:126
[9] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt52{UInt64}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:125
[10] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt23{UInt32}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:124
[11] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt10{UInt16}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:123
[12] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt23Raw{UInt32}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:112
[13] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt10Raw{UInt16}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:111
[14] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.CloseOpen01{Float64}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:35
[15] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.CloseOpen01{Float32}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:29
[16] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.CloseOpen01{Float16}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:25
[17] rand(rng::Random.AbstractRNG, sp::Random.SamplerTrivial{Tuple{A}, E} where E) where A in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:495
[18] rand(rng::Random.AbstractRNG, sp::Random.SamplerRangeNDL{U, T}) where {U, T} in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:330
[19] rand(r::Random.AbstractRNG, ::Random.SamplerType{Complex{T}}) where T<:Real in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:159
[20] rand(r::Random.AbstractRNG, ::Random.SamplerType{T}) where T<:AbstractChar in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:165
[21] rand

In [14]:
using Distributions

In [15]:
methods(rand)

# 169 methods for generic function "rand":
[1] rand() in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:256
[2] rand(dims::Integer...) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:277
[3] rand(d::UnivariateGMM) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/mixtures/unigmm.jl:28
[4] rand(d::NoncentralF) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/univariate/continuous/noncentralf.jl:58
[5] rand(d::NoncentralF, n::Int64) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/common.jl:176
[6] rand(rng::Random.AbstractRNG, d::Frechet) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/univariate/continuous/frechet.jl:142
[7] rand(rng::Random.AbstractRNG, d::NoncentralF) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/univariate/continuous/noncentralf.jl:50
[8] rand(rng::Random.AbstractRNG, d::Skellam) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/univariate/discrete/skellam.jl:111
[9] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt104{UInt128}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:126
[10] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt52{UInt64}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:125
[11] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt23{UInt32}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:124
[12] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt10{UInt16}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:123
[13] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt23Raw{UInt32}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:112
[14] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.UInt10Raw{UInt16}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:111
[15] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.CloseOpen01{Float64}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:35
[16] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.CloseOpen01{Float32}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:29
[17] rand(r::Random.AbstractRNG, ::Random.SamplerTrivial{Random.CloseOpen01{Float16}, E} where E) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:25
[18] rand(rng::Random.AbstractRNG, sp::Random.SamplerTrivial{Tuple{A}, E} where E) where A in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:495
[19] rand(rng::Random.AbstractRNG, d::Gamma) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/univariate/continuous/gamma.jl:90
[20] rand(rng::Random.AbstractRNG, X::Tuple{Vararg{Int64, N}} where N) in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/Random.jl:255
[21] rand(rng::Random.AbstractRNG, sp::Random.SamplerRangeInt{T, UInt32}) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Random at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Random/src/generation.jl:294
[22] rand(rng::Random.AbstractRNG, sp::Random.SamplerRangeInt

In [1]:
methods(+)

# 190 methods for generic function "+":
[1] +(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[2] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:528
[3] +(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:534
[4] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:376
[5] +(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:384
[6] +(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:392
[7] +(x::Union{Dates.CompoundPeriod, Dates.Period}) in Dates at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Dates/src/periods.jl:362
[8] +(Da::LinearAlgebra.Diagonal, Db::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:156
[9] +(D::LinearAlgebra.Diagonal, S::LinearAlgebra.Symmetric) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:160
[10] +(D::LinearAlgebra.Diagonal{var"#s832", V} where {var"#s832"<:Real, V<:AbstractVector{var"#s832"}}, H::LinearAlgebra.Hermitian) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:166
[11] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:125
[12] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.SymTridiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:135
[13] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Tridiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:163
[14] +(A::LinearAlgebra.Diagonal{var"#s832", V} where {var"#s832"<:Number, V<:AbstractVector{var"#s832"}}, B::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:241
[15] +(A::LinearAlgebra.UnitUpperTriangular, B::LinearAlgebra.UpperTriangular) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:652
[16] +(A::LinearAlgebra.UnitUpperTriangular, B::LinearAlgebra.UnitUpperTriangular) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:654
[17] +(UL::LinearAlgebra.UnitUpperTriangular, J::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/uniformscaling.jl:182
[18] +(A::LinearAlgebra.UnitUpperTriangular, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:86
[19] +(y::Dates.TimeType, x::StridedArray{var"#s832", N} where {var"#s832"<:Union{Dates.CompoundPeriod, Dates.Period}, N}) in Dates at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Dates/src/deprecated.jl:18
[20] +(r1::LinRange{T}, r2::LinRange{T}) where T in Base at range.jl:1108
[21] +(A::BitArray, B::BitArray) in Base at bitarray.jl:1127
[22] +(r1::OrdinalRange, r2::OrdinalRange) in Base at range.jl:1101
[23] +(A::LinearAlgebra.UnitLowerTriangular, B::LinearAlgebra.LowerTriangular) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:653
[24] +(A::LinearAlgebra.UnitLowerTriangular, B::LinearAlgebra.UnitLowerTriangular) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:655
[25] +(UL::LinearAlgebra.

In [2]:
using Distributions

In [3]:
methods(+)

# 271 methods for generic function "+":
[1] +(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[2] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:528
[3] +(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:534
[4] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:376
[5] +(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:384
[6] +(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:392
[7] +(x::Union{Dates.CompoundPeriod, Dates.Period}) in Dates at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Dates/src/periods.jl:362
[8] +(d::MvNormal, c::AbstractVector{T} where T) in Distributions at /Users/uqjnazar/.julia/packages/Distributions/fXTVC/src/multivariate/mvnormal.jl:271
[9] +(a::ChainRulesCore.Tangent{P, T} where T, b::ChainRulesCore.Tangent{P, T} where T) where P in ChainRulesCore at /Users/uqjnazar/.julia/packages/ChainRulesCore/GciYT/src/differential_arithmetic.jl:145
[10] +(a::ChainRulesCore.Tangent, b::ChainRulesCore.AbstractThunk) in ChainRulesCore at /Users/uqjnazar/.julia/packages/ChainRulesCore/GciYT/src/differential_arithmetic.jl:139
[11] +(a::ChainRulesCore.Tangent, ::ChainRulesCore.ZeroTangent) in ChainRulesCore at /Users/uqjnazar/.julia/packages/ChainRulesCore/GciYT/src/differential_arithmetic.jl:116
[12] +(a::ChainRulesCore.Tangent, ::ChainRulesCore.NoTangent) in ChainRulesCore at /Users/uqjnazar/.julia/packages/ChainRulesCore/GciYT/src/differential_arithmetic.jl:76
[13] +(::ChainRulesCore.Tangent, x::ChainRulesCore.NotImplemented) in ChainRulesCore at /Users/uqjnazar/.julia/packages/ChainRulesCore/GciYT/src/differential_arithmetic.jl:26
[14] +(a::ChainRulesCore.Tangent{P, T} where T, b::P) where P in ChainRulesCore at /Users/uqjnazar/.julia/packages/ChainRulesCore/GciYT/src/differential_arithmetic.jl:162
[15] +(Da::LinearAlgebra.Diagonal, Db::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:156
[16] +(D::LinearAlgebra.Diagonal, S::LinearAlgebra.Symmetric) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:160
[17] +(D::LinearAlgebra.Diagonal{var"#s832", V} where {var"#s832"<:Real, V<:AbstractVector{var"#s832"}}, H::LinearAlgebra.Hermitian) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:166
[18] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:125
[19] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.SymTridiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:135
[20] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Tridiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:163
[21] +(A::LinearAlgebra.Diagonal{var"#s832", V} where {var"#s832"<:Number, V<:AbstractVector{var"#s832"}}, B::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:241
[22] +(a::PDMats.AbstractPDMat, b::LinearAlgebra.UniformScaling) in PDMats at /Users/uqjnazar/.julia/packages/PDMats/vgpB7/src/addition.jl:42
[23] +(a::PDMats.AbstractPDMat, b::Matrix{T} where T) in PDMats at /Users/uqjnazar/.julia/packages/PDMats/vgpB7/src/generics.jl:23
[24] +(A::LinearAlgebra.UnitUpperTriangular, B::LinearAlgebra.UpperTriangular) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:652
[25] +(A::LinearAlgebra.UnitUpp

In [4]:
nothing

In [5]:
typeof(nothing)

Nothing

In [6]:
my_f(x,y,z) = x + y + z

my_f (generic function with 1 method)

In [7]:
data = [1,2,3]
my_f(data)

LoadError: MethodError: no method matching my_f(::Vector{Int64})
Closest candidates are:
  my_f(::Any, ::Any, ::Any) at In[6]:1

In [8]:
my_f(data...)

6

In [9]:
?min  #different from minimum

search: min minmax minimum minimum! argmin Main typemin findmin findmin!



```
min(x, y, ...)
```

Return the minimum of the arguments. See also the [`minimum`](@ref) function to take the minimum element from a collection.

# Examples

```jldoctest
julia> min(2, 5, 1)
1
```


In [12]:
min(2,3,-1)

-1

In [18]:
my_min(data) = begin
    @show length(data) #for debug
    min(data...)
end

my_min (generic function with 1 method)

In [14]:
data

3-element Vector{Int64}:
 1
 2
 3

In [15]:
min(data) #system min doesn't work on an array (use minimum)

LoadError: MethodError: no method matching min(::Vector{Int64})
Closest candidates are:
  min(::Any, ::Missing) at missing.jl:127
  min(::Any, ::Any) at operators.jl:433
  min(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  ...

In [19]:
my_min(data)

length(data) = 3


1

In [23]:
using Roots

function polynomialGenerator(a...)
    n = length(a)-1
    poly(x) = sum(a[i+1]*x^i for i in 0:n)
    return poly
end

polynomial = polynomialGenerator(1,3,-10)
zero_vals = find_zeros(polynomial,-10,10)
println("Zeros of the function f(x): ", zero_vals)

Zeros of the function f(x): [-0.19999999999999998, 0.5]


In [24]:
my_density(x::Float64, μ::Float64 = 0.0, σ::Float64 = 1.0) = exp(-(x-μ)^2/(2σ^2) ) / (σ*√(2π)) 

my_density (generic function with 3 methods)

In [25]:
methods(my_density)

# 3 methods for generic function "my_density":
[1] my_density(x::Float64) in Main at In[24]:1
[2] my_density(x::Float64, μ::Float64) in Main at In[24]:1
[3] my_density(x::Float64, μ::Float64, σ::Float64) in Main at In[24]:1

In [26]:
Normal()

Normal{Float64}(μ=0.0, σ=1.0)

In [ ]:
using Distributions
x = 1.5
@show pdf(Normal(),x), my_density(x)
@show pdf(Normal(0.5),x), my_density(x,0.5);

In [27]:
my_density(x::Float64 ; μ::Float64 = 0.0, σ::Float64 = 1.0) = exp(-(x-μ)^2/(2σ^2) ) / (σ*√(2π)) 

my_density (generic function with 3 methods)

In [28]:
my_density(2.5;σ = 5.3,μ=2.3)

0.07521855391129509

In [29]:
my_density(2.5;μ=2.3,σ = 5.3)

0.07521855391129509

In [30]:
my_density(2.5, μ=2.3,σ = 5.3)

0.07521855391129509

In [34]:
function my_very_flexible_function(x::Number;kwargs...)
    println(kwargs)
    for arg in kwargs
        @show arg
    end
end

my_very_flexible_function(2.5,a=1,b="two",c=:three)

Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:a, :b, :c), Tuple{Int64, String, Symbol}}}(:a => 1, :b => "two", :c => :three)
arg = Pair{Symbol, Any}(:a, 1)
arg = Pair{Symbol, Any}(:b, "two")
arg = Pair{Symbol, Any}(:c, :three)


In [35]:
? filter

search: filter filter! fieldtype fieldtypes



```
filter(f, a)
```

Return a copy of collection `a`, removing elements for which `f` is `false`. The function `f` is passed one argument.

!!! compat "Julia 1.4"
    Support for `a` as a tuple requires at least Julia 1.4.


# Examples

```jldoctest
julia> a = 1:10
1:10

julia> filter(isodd, a)
5-element Vector{Int64}:
 1
 3
 5
 7
 9
```

---

```
filter(f, d::AbstractDict)
```

Return a copy of `d`, removing elements for which `f` is `false`. The function `f` is passed `key=>value` pairs.

# Examples

```jldoctest
julia> d = Dict(1=>"a", 2=>"b")
Dict{Int64, String} with 2 entries:
  2 => "b"
  1 => "a"

julia> filter(p->isodd(p.first), d)
Dict{Int64, String} with 1 entry:
  1 => "a"
```

---

```
filter(f, itr::SkipMissing{<:AbstractArray})
```

Return a vector similar to the array wrapped by the given `SkipMissing` iterator but with all missing elements and those for which `f` returns `false` removed.

!!! compat "Julia 1.2"
    This method requires Julia 1.2 or later.


# Examples

```jldoctest
julia> x = [1 2; missing 4]
2×2 Matrix{Union{Missing, Int64}}:
 1         2
  missing  4

julia> filter(isodd, skipmissing(x))
1-element Vector{Int64}:
 1
```


In [37]:
filter(rand(10)) do x 
                    return false
end

Float64[]

In [38]:
? broadcast

search: broadcast broadcast! Broadcast



```
broadcast(f, As...)
```

Broadcast the function `f` over the arrays, tuples, collections, [`Ref`](@ref)s and/or scalars `As`.

Broadcasting applies the function `f` over the elements of the container arguments and the scalars themselves in `As`. Singleton and missing dimensions are expanded to match the extents of the other arguments by virtually repeating the value. By default, only a limited number of types are considered scalars, including `Number`s, `String`s, `Symbol`s, `Type`s, `Function`s and some common singletons like [`missing`](@ref) and [`nothing`](@ref). All other arguments are iterated over or indexed into elementwise.

The resulting container type is established by the following rules:

  * If all the arguments are scalars or zero-dimensional arrays, it returns an unwrapped scalar.
  * If at least one argument is a tuple and all others are scalars or zero-dimensional arrays, it returns a tuple.
  * All other combinations of arguments default to returning an `Array`, but custom container types can define their own implementation and promotion-like rules to customize the result when they appear as arguments.

A special syntax exists for broadcasting: `f.(args...)` is equivalent to `broadcast(f, args...)`, and nested `f.(g.(args...))` calls are fused into a single broadcast loop.

# Examples

```jldoctest
julia> A = [1, 2, 3, 4, 5]
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> B = [1 2; 3 4; 5 6; 7 8; 9 10]
5×2 Matrix{Int64}:
 1   2
 3   4
 5   6
 7   8
 9  10

julia> broadcast(+, A, B)
5×2 Matrix{Int64}:
  2   3
  5   6
  8   9
 11  12
 14  15

julia> parse.(Int, ["1", "2"])
2-element Vector{Int64}:
 1
 2

julia> abs.((1, -2))
(1, 2)

julia> broadcast(+, 1.0, (0, -2.0))
(1.0, -1.0)

julia> (+).([[0,2], [1,3]], Ref{Vector{Int}}([1,-1]))
2-element Vector{Vector{Int64}}:
 [1, 1]
 [2, 2]

julia> string.(("one","two","three","four"), ": ", 1:4)
4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

```


In [39]:
? map

search: map map! mapfoldr mapfoldl mapslices mapreduce asyncmap asyncmap!



```
map(f, c...) -> collection
```

Transform collection `c` by applying `f` to each element. For multiple collection arguments, apply `f` elementwise.

See also: [`mapslices`](@ref)

# Examples

```jldoctest
julia> map(x -> x * 2, [1, 2, 3])
3-element Vector{Int64}:
 2
 4
 6

julia> map(+, [1, 2, 3], [10, 20, 30])
3-element Vector{Int64}:
 11
 22
 33
```


In [41]:
@assert 2+3 == 6

LoadError: AssertionError: 2 + 3 == 6